/**
 * Copyright (C) 2019 Greenweaves Software Limited
 *
 * This is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this software.  If not, see <http://www.gnu.org/licenses/>
 *
 * This file exercises serialization. 
 */
 
 #include "catch.hpp"
 #include "utils.h"


 TEST_CASE( "Serialization Tests", "[serialization]" ) {
	 
	 SECTION("Parse float") {  // generated by configure.py --generate
		REQUIRE(decode2("-4009ca63ad901934")==-3.2238229331589086);
		REQUIRE(decode2("400c25dbc7f984fc")==3.518485605528097);
		REQUIRE(decode2("4002c41e7a4dcde0")==2.3457612566942174);
		REQUIRE(decode2("4011a268b1ca7af8")==4.408602502807064);
		REQUIRE(decode2("400005e07e8ddf34")==2.0028695952459206);
		REQUIRE(decode2("-3fd8b9bce7244d40")==-0.38633654186670086);
		REQUIRE(decode2("-3fd81f6d7f337320")==-0.376918195934012);
		REQUIRE(decode2("-400d4affe24fd278")==-3.6616208725557122);
		REQUIRE(decode2("3ffd44e2c6a2c4e8")==1.82931783287159);
		REQUIRE(decode2("3ffff242d7d2e024")==1.99664577776094);
		REQUIRE(decode2("-3fe3be17c3da9500")==-0.6169546914358364);
		REQUIRE(decode2("-3ff2f1deb582df90")==-1.1840502825052432);
		REQUIRE(decode2("400da58ad3db245c")==3.7058311988117065);
		REQUIRE(decode2("40091090a26ca900")==3.1330883683596085);
		REQUIRE(decode2("-400029dfb01e25dc")==-2.0204461821747213);
		REQUIRE(decode2("400dabcb4eb15904")==3.7088838718292454);
		REQUIRE(decode2("3fe5910e5d1f6430")==0.6739570444871159);
		REQUIRE(decode2("-400cb00866c0a7f7")==-3.5859535243553142);
		REQUIRE(decode2("400a45b494a1bab0")==3.284035836396775);
		REQUIRE(decode2("-4006b879370cbe4c")==-2.8400749493373834);

	}
 }